### ISSUE TITLE
error when requiring menuitem

### ISSUE THREAD

**Issue by nikolas** [jetpack-labs/menuitem#3]
Using menuitem 0.0.4 and jpm 1.0.0, I'm calling menuitem like this:

```js
        var menuitem = require("menuitem").Menuitem({
            id: 'librejs_settings',
            menuid: 'menu_ToolsPopup',
            label: 'LibreJS Whitelist',
            onCommand: function() {
                settings_tab.settingsManager.open();
            },
            insertBefore: "menu_pageInfo"
        });
```

and I'm getting this error:

```
console.error: librejs: 
  Message: Module `menuitem` is not found at resource://gre/modules/commonjs/menuitem.js
  Stack:
    exports.UI.init@resource://jid1-ktlzuoiikvffew-at-jetpack/lib/ui.js:140:24
```

It's probably some stupid mistake I'm making somewhere.
